name: Release binaries for all platforms

on:
    push:
      tags:
        - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: cargo check
        run: cargo check

      - name: Build release
        run: cargo build --release

      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            target/release/iplookup.exe

  cross-compile-on-macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2

      - name: cargo check
        run: rustup target add aarch64-apple-darwin &&
          cargo check

      - name: Build release
        run: cargo build --release --target aarch64-apple-darwin

      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            target/aarch64-apple-darwi/release/iplookup

      - name: install linux cross compiler
        run: brew tap messense/macos-cross-toolchains &&
          brew install x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu arm-unknown-linux-gnueabihf armv7-unknown-linux-gnueabihf

      - name: Build release linux x86_64
        run: rustup target install x86_64-unknown-linux-gnu &&
          cargo build --release --target x86_64-unknown-linux-gnu

      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            target/x86_64-unknown-linux-gnu/release/iplookup

      - name: Build release linux armv6
        run: rustup target install arm-unknown-linux-gnueabihf &&
            cargo build --release --target arm-unknown-linux-gnueabihf

      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            target/arm-unknown-linux-gnueabihf/release/iplookup

      - name: Build release linux armv7
        run: rustup target install armv7-unknown-linux-gnueabihf &&
            cargo build --release --target armv7-unknown-linux-gnueabihf

      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            target/armv7-unknown-linux-gnueabihf/release/iplookup

      - name: Build release linux aarch64
        run: rustup target install aarch64-unknown-linux-gnu &&
            cargo build --release --target aarch64-unknown-linux-gnu

      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            target/aarch64-unknown-linux-gnu/release/iplookup
    env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
