name: Release binaries for all platforms

on:
    push:
      tags:
        - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: cargo check
        run: cargo check

      - name: Build release
        run: cargo build --release

      - name: Compression
        run: 7z a -tzip iplookup_windows_x86_64.zip target/release/iplookup.exe

      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            target/release/iplookup.exe

  release-macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2

      - name: cargo check
        run: rustup target add aarch64-apple-darwin &&
          cargo check
    
      - name: look
        run: tree .

      - name: Build release
        run: cargo build --release --target aarch64-apple-darwin

      - name: Compression
        run: zip -j iplookup_macos_arm64.zip target/release/iplookup

      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            target/release/iplookup

  release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: cargo check
        run: rustup target add x86_64-unknown-linux-gnu &&
          cargo check

      - name: look
        run: tree .

      - name: Build release
        run: cargo build --release

      - name: Compression
        run: zip -j iplookup_linux_x86_64.zip target/release/iplookup

      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            target/release/iplookup

    env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
